# Generated by Django 4.2.7 on 2025-09-01 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learning_goals', models.JSONField(default=list, help_text='List of learning goals')),
                ('career_goals', models.TextField(blank=True, help_text='Career goals and aspirations')),
                ('current_level', models.CharField(choices=[('student', 'Student'), ('early_career', 'Early Career'), ('mid_career', 'Mid Career'), ('career_changer', 'Career Changer')], default='student', max_length=20)),
                ('preferred_mentor_qualities', models.JSONField(default=list, help_text='Preferred mentor qualities')),
                ('preferred_meeting_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('flexible', 'Flexible')], default='weekly', max_length=20)),
                ('total_mentors', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, help_text='Mentee bio')),
                ('motivation', models.TextField(blank=True, help_text='Why they want to be mentored')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mentee Profile',
                'verbose_name_plural': 'Mentee Profiles',
                'db_table': 'mentorship_mentee_profile',
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expertise_areas', models.JSONField(default=list, help_text='List of expertise areas')),
                ('years_experience', models.IntegerField(default=0, help_text='Years of professional experience')),
                ('preferred_mentee_level', models.CharField(choices=[('student', 'Student'), ('early_career', 'Early Career'), ('mid_career', 'Mid Career'), ('any', 'Any Level')], default='any', max_length=20)),
                ('max_mentees', models.IntegerField(default=3, help_text='Maximum number of active mentees')),
                ('available_for_mentorship', models.BooleanField(default=True)),
                ('total_mentees_helped', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sessions', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, help_text='Mentor bio')),
                ('motivation', models.TextField(blank=True, help_text='Why they want to mentor')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mentor Profile',
                'verbose_name_plural': 'Mentor Profiles',
                'db_table': 'mentorship_mentor_profile',
            },
        ),
        migrations.CreateModel(
            name='MentorshipProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Program name', max_length=255)),
                ('description', models.TextField(help_text='Program description')),
                ('program_type', models.CharField(choices=[('career', 'Career Development'), ('technical', 'Technical Skills'), ('leadership', 'Leadership'), ('academic', 'Academic'), ('personal', 'Personal Development')], default='career', max_length=50)),
                ('max_mentees_per_mentor', models.IntegerField(default=5, help_text='Maximum number of mentees per mentor')),
                ('program_duration_weeks', models.IntegerField(default=12, help_text='Program duration in weeks')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('start_date', models.DateField(help_text='Program start date')),
                ('end_date', models.DateField(help_text='Program end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mentorship Program',
                'verbose_name_plural': 'Mentorship Programs',
                'db_table': 'mentorship_program',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('goals', models.JSONField(default=list, help_text='Specific goals for this mentorship')),
                ('expectations', models.TextField(blank=True, help_text='Mentorship expectations')),
                ('preferred_meeting_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('flexible', 'Flexible')], default='weekly', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('mentee_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('mentor_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_relationships', to='mentorship.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_relationships', to='mentorship.mentorprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='mentorship.mentorshipprogram')),
            ],
            options={
                'verbose_name': 'Mentorship Relationship',
                'verbose_name_plural': 'Mentorship Relationships',
                'db_table': 'mentorship_relationship',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Session title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Session description')),
                ('scheduled_date', models.DateTimeField(help_text='Scheduled session date/time')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Session duration in minutes')),
                ('meeting_link', models.URLField(blank=True, help_text='Meeting link')),
                ('meeting_platform', models.CharField(blank=True, help_text='Meeting platform (Zoom, Google Meet, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('agenda', models.JSONField(blank=True, default=list, help_text='Session agenda items')),
                ('notes', models.TextField(blank=True, help_text='Session notes')),
                ('action_items', models.JSONField(blank=True, default=list, help_text='Action items from the session')),
                ('mentee_feedback', models.TextField(blank=True)),
                ('mentor_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorship.mentorshiprelationship')),
            ],
            options={
                'verbose_name': 'Mentorship Session',
                'verbose_name_plural': 'Mentorship Sessions',
                'db_table': 'mentorship_session',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
