# Generated by Django 4.2.7 on 2025-09-01 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Career path name', max_length=255)),
                ('description', models.TextField(help_text='Career path description')),
                ('industry', models.CharField(help_text='Industry sector', max_length=100)),
                ('level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead'), ('executive', 'Executive')], default='entry', max_length=20)),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills for this career path')),
                ('recommended_skills', models.JSONField(default=list, help_text='List of recommended skills for this career path')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'db_table': 'career_career_path',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True, help_text='Cover letter')),
                ('resume_url', models.URLField(blank=True, help_text='Resume/CV URL')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Under Review'), ('interviewing', 'Interviewing'), ('offered', 'Offer Made'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('is_active', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'career_job_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Job title', max_length=255)),
                ('company', models.CharField(help_text='Company name', max_length=255)),
                ('description', models.TextField(help_text='Job description')),
                ('requirements', models.TextField(help_text='Job requirements')),
                ('responsibilities', models.TextField(help_text='Job responsibilities')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive')], default='entry', max_length=20)),
                ('location', models.CharField(help_text='Job location', max_length=255)),
                ('is_remote', models.BooleanField(default=False, help_text='Whether job is remote')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary', max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', help_text='Salary currency code', max_length=3)),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills')),
                ('preferred_skills', models.JSONField(default=list, help_text='List of preferred skills')),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Application deadline', null=True)),
                ('application_url', models.URLField(blank=True, help_text='External application URL')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('applications_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'db_table': 'career_job_posting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Skill name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Skill description')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('domain', 'Domain Knowledge'), ('tool', 'Tools & Technologies')], default='technical', max_length=20)),
                ('subcategory', models.CharField(blank=True, help_text='Skill subcategory', max_length=100)),
                ('difficulty_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='Skill difficulty level (1-5)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'career_skill',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('years_experience', models.DecimalField(decimal_places=1, default=0, help_text='Years of experience with this skill', max_digits=3)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether skill is verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio_items', models.JSONField(blank=True, default=list, help_text='Portfolio items demonstrating this skill')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='career.skill')),
            ],
            options={
                'verbose_name': 'User Skill',
                'verbose_name_plural': 'User Skills',
                'db_table': 'career_user_skill',
            },
        ),
    ]
